/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lkrawiec.myprojects.datastorage.view;

/**
 * Panel containing two buttons with save and back options.
 * 
 * @author Lukasz Krawiec
 */
public class ButtonsPanel extends javax.swing.JPanel {

    /** Action to be performed on save button */
    private Action saveAction;
    /** Action to be performed on back button */
    private Action backAction;

    /** 
     * Setter for save action button.
     * 
     * @param saveAction given action
     */
    public void setSaveAction(Action saveAction) {
        this.saveAction = saveAction;
    }

    /**
     * Setter for back action button.
     * 
     * @param backAction given action
     */
    public void setBackAction(Action backAction) {
        this.backAction = backAction;
    }
    
    /**
     * Creates new form ButtonsPanel
     */
    public ButtonsPanel() {
        initComponents();
    }

    /**
     * Sets if save button will be visible.
     * 
     * @param visible visibility to be set
     */
    public void setSaveButtonVisible(boolean visible) {
        saveButton.setVisible(visible);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(saveButton, gridBagConstraints);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(backButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Fires action on back button press.
     * 
     * @param evt given action
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        backAction.Do();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * Fires action on save button press.
     * 
     * @param evt given action
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveAction.Do();
    }//GEN-LAST:event_saveButtonActionPerformed


    /**
     * Elements of UI
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
