/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lkrawiec.myprojects.datastorage.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 * Main frame of the application. Everything will be shown inside this frame.
 * Has two panels that will be changed depending on current state of View.
 * @author Lukasz Krawiec
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Initialisates GUIFrame components
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        firstPanel = new javax.swing.JPanel();
        secondPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        firstPanel.setBorder(new javax.swing.border.MatteBorder(null));
        firstPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        firstPanel.setMinimumSize(new java.awt.Dimension(640, 480));
        firstPanel.setPreferredSize(new java.awt.Dimension(640, 480));
        firstPanel.setLayout(new javax.swing.BoxLayout(firstPanel, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(firstPanel, gridBagConstraints);

        secondPanel.setBorder(new javax.swing.border.MatteBorder(null));
        secondPanel.setMaximumSize(new java.awt.Dimension(1920, 60));
        secondPanel.setMinimumSize(new java.awt.Dimension(640, 60));
        secondPanel.setName(""); // NOI18N
        secondPanel.setPreferredSize(new java.awt.Dimension(640, 60));
        secondPanel.setLayout(new javax.swing.BoxLayout(secondPanel, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(secondPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Removes everything inside upper panel and sets it with given
     * panel. Makes panel visible. If method is called with null, hides upper 
     * panel.
     * 
     * @param panel given panel
     */
    public void setFirstPanel(JPanel panel) {
        firstPanel.removeAll();
        if (panel != null) {
            firstPanel.add(panel);
            firstPanel.setVisible(true);
        } else {
            firstPanel.setVisible(false);
        }
    }

    /**
     * Removes everything inside lower panel and sets it with given
     * panel. Makes panel visible. If method is called with null, hides lower 
     * panel.
     * 
     * @param panel given panel
     */
    public void setSecondPanel(JPanel panel) {
        secondPanel.removeAll();
        if (panel != null) {
            secondPanel.add(panel);
            secondPanel.setVisible(true);
        } else {
            secondPanel.setVisible(false);
        }
    }
    
    /**
     * Sets GUI visible
     */
    public void startGUI() {
        setVisible(true);       
    }

    /**
     * UI elements
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel firstPanel;
    private javax.swing.JPanel secondPanel;
    // End of variables declaration//GEN-END:variables
}
