/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lkrawiec.myprojects.datastorage.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author lukii
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        firstPanel = new javax.swing.JPanel();
        secondPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        firstPanel.setBorder(new javax.swing.border.MatteBorder(null));
        firstPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        firstPanel.setMinimumSize(new java.awt.Dimension(640, 480));
        firstPanel.setPreferredSize(new java.awt.Dimension(640, 480));
        firstPanel.setLayout(new javax.swing.BoxLayout(firstPanel, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(firstPanel, gridBagConstraints);

        secondPanel.setBorder(new javax.swing.border.MatteBorder(null));
        secondPanel.setMaximumSize(new java.awt.Dimension(1920, 60));
        secondPanel.setMinimumSize(new java.awt.Dimension(640, 60));
        secondPanel.setName(""); // NOI18N
        secondPanel.setPreferredSize(new java.awt.Dimension(640, 60));
        secondPanel.setLayout(new javax.swing.BoxLayout(secondPanel, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(secondPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        GUIFrame frame = new GUIFrame();
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //test
//                
//                frame.setFirstPanel(new ChangeFormPanel());
//                frame.setSecondPanel(new ButtonsPanel());
//                frame.setVisible(true);
//            }
//        });
//        
//        try {
//            Thread.sleep(5000);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        java.awt.EventQueue.invokeLater(() -> {
//            //test
//            
//            frame.setFirstPanel(new MainPanel());
//            frame.setSecondPanel(new ButtonsPanel());
//            frame.setVisible(true);
//        });
//        
//        try {
//            Thread.sleep(5000);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        java.awt.EventQueue.invokeLater(() -> {
//            //test
//            HistoryPanel hp = new HistoryPanel();
//            hp.setSecondPanel(new ChangeFormPanel());
//            frame.setFirstPanel(hp);
//            frame.setSecondPanel(new ButtonsPanel());
//            frame.setVisible(true);
//        });
//    }
    public void setFirstPanel(JPanel panel) {
        firstPanel.removeAll();
        if (panel != null) {
            firstPanel.add(panel);
            firstPanel.setVisible(true);
        } else {
            firstPanel.setVisible(false);
        }
    }

    public void setSecondPanel(JPanel panel) {
        secondPanel.removeAll();
        if (panel != null) {
            secondPanel.add(panel);
            secondPanel.setVisible(true);
        } else {
            secondPanel.setVisible(false);
        }
    }
    
    public void startGUI() {
        setVisible(true);       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel firstPanel;
    private javax.swing.JPanel secondPanel;
    // End of variables declaration//GEN-END:variables
}
