/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lkrawiec.myprojects.datastorage.view;

/**
 *
 * @author lukii
 */
public class MainPanel extends javax.swing.JPanel {

    private Action addChangeButtonAction;
    private Action searchCarButtonAction;

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    public void setAddChangeButtonAction(Action addChangeButtonAction) {
        this.addChangeButtonAction = addChangeButtonAction;
    }

    public void setSearchCarButtonAction(Action searchCarButtonAction) {
        this.searchCarButtonAction = searchCarButtonAction;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        newChangeButton = new javax.swing.JButton();
        searchCarButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        newChangeButton.setText("New Change");
        newChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newChangeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(newChangeButton, gridBagConstraints);

        searchCarButton.setText("Search Car");
        searchCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(searchCarButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void newChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newChangeButtonActionPerformed
        addChangeButtonAction.Do();
    }//GEN-LAST:event_newChangeButtonActionPerformed

    private void searchCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCarButtonActionPerformed
        searchCarButtonAction.Do();
    }//GEN-LAST:event_searchCarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newChangeButton;
    private javax.swing.JButton searchCarButton;
    // End of variables declaration//GEN-END:variables
}
